---
title: "Simulating data for the Ontario restaurant closures experiment"
author: "Lorena Almaraz De La Garza, Amy Farrow, and Kumalasari Sondjaja"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::pdf_document2:
    toc: no
subtitle: "SUBTITLE"
abstract: "This document explains how data for the Ontario restaurant closures experiment was simulated, including the research that was used for parameterization and the methods used to randomize data."
thanks: 'Code and data are available at: [github.com/amycfarrow/ontariorestaurantclosuresexperiment](https://github.com/amycfarrow/ontariorestaurantclosuresexperiment).'
bibliography: references.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(bookdown)    # for cross referencing figures and graphs; referencing
library(kableExtra)  # for nicer tables
library(here) # for working in projects

```

```{r}
all_units_data <- read_csv(here::here("outputs/data/all_units_data.csv"))

all_units_data <- all_units_data %>%
  mutate(group = case_when(unit == "brant" ~ "treatment",
                           unit == "peel" ~ "treatment",
                           unit == "sudbury" ~ "treatment",
                           unit == "hamilton" ~ "control",
                           unit == "southwestern" ~ "control",
                           unit == "chatham" ~ "control"
                           ))

num_treat <- first(count(all_units_data %>%
                   filter(group == "treatment")))

num_control <- first(count(all_units_data %>%
                   filter(group == "control")))

num_total <- first(count(all_units_data))

survey_1 <- all_units_data

survey_2 <- all_units_data

```



# Survey questions that require simulated data

# Type of service provided
LORENA
## Survey 1
```{r}

```

## Survey 2
```{r}

```


# Number of employees
LALA
## Survey 1
```{r}

```

## Survey 2
```{r}

```


# Revenue

## Survey 1
```{r}

```

## Survey 2
```{r}

```


# Applications for government assistance
LORENA
## Survey 1
```{r}

```

## Survey 2
```{r}

```


# Demographic traits of owners
AMY AND LALA
## Survey 1
```{r}

```

## Survey 2
```{r}

```

\newpage

# References