---
title: "TITLE"
author: "Lorena Almaraz De La Garza, Amy Farrow, and Kumalasari Sondjaja"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::pdf_document2:
    toc: no
subtitle: "SUBTITLE"
abstract: "ABSTRACT"
thanks: 'Code and data are available at: [github.com/amycfarrow/ontariorestaurantclosuresexperiment](https://github.com/amycfarrow/ontariorestaurantclosuresexperiment).'
bibliography: references.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(bookdown)    # for cross referencing figures and graphs; referencing
library(kableExtra)  # for nicer tables

```


# Introduction





# Data

```{r}
treatment_control_groups
```

```{r}
all_units_data
```

```{r}
table_for_surveys
```

```{r}

```


# Discussion

## Overview




## Findings

### FINDING ONE
 Closures had a negative impact


### FINDING TWO
Closures had a stronger negative impact on dine-in only restaurants


### FINDING THREE
CLosures had a stronger negative impact on POC-owned



## Limitations




## Future Directions






\newpage

# References