---
title: "R Notebook"
output: html_notebook
---


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(bookdown)
library(kableExtra)
library(here)

#REPLACE LINE 81 WITH:
```
This survey cost $5,606. A detailed breakdown of costs can be found on [Appendix X](#appendixX).
```{r}
#INCLUDE IN APPENDIX [REPLACE X WITH CORRECT NUMBER, AFTER SURVEY APPENDIX]
```
# Appendix X {#appendixX}
```{r echo=FALSE, message=FALSE, warning=FALSE}
restaurants = 2006
survey_total = 2
indiv_postage = 0.85 # https://www.canadapost.ca/cpc/en/business/postal-services/mailing/letter-discounts.page?
minimum_wage = 14.25 # https://www.ontario.ca/document/your-guide-employment-standards-act-0/minimum-wage
management_service = 195 # https://www.alchemer.com/plans-pricing/small-teams/
average_call_mins = 7
response_rate = .3 

phone_interviewer_cost = round(restaurants*survey_total*response_rate, 2)*average_call_mins/60*minimum_wage

postage_cost = (restaurants*2)*indiv_postage

survey_budget <- data.frame(
  Item = c ("Data Management", "Phone Interviewer Wages", "Postage", "TOTAL"),
  Cost = c (management_service, phone_interviewer_cost, postage_cost, sum(management_service, phone_interviewer_cost, postage_cost)),
  Description = c ("Online survey management account fees",
                   "1,203 calls (7 minutes on average) at $14.25/hr",
                   "4,012 mailers at $0.85/ea",
                   "")
)

survey_budget %>% 
  kable(digits = 2,
        caption = "2021 Ontario Restaurant Survey Budget") %>% 
  kable_styling() %>% 
  row_spec(0, bold = T, color = "white", background = "grey") %>% 
  row_spec(4, bold = T)
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
#GRAPHS SURVEY 1

survey_1 <- read_csv(here("outputs/data/survey_1.csv"))

ggplot(survey_1, aes(x = service_type, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = disability, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = woman, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = visible, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = revenue, fill = group)) +                       
  geom_histogram(position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = ft, fill = group)) +                       
  geom_histogram(position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = pt, fill = group)) +                       
  geom_histogram(position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()


survey_1 %>%
  group_by(group, service_type) %>%
  summarise(count_service_type = n(),
  ) %>%
  mutate(perc_service_type = count_service_type / sum(count_service_type)) %>%
  ggplot(aes(x = service_type, y = perc_service_type, fill = group)) +                       
  geom_bar(stat = "identity", position = "dodge", alpha = 0.5, bins = 50) +
  theme_minimal()


ggplot(survey_1, aes(x = service_type, fill = group)) +                       
  geom_histogram(stat = "count", position = "dodge", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = disability, fill = group)) +                       
  geom_histogram(stat = "count", position = "dodge", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = woman, fill = group)) +                       
  geom_histogram(stat = "count", position = "dodge", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_1, aes(x = visible, fill = group)) +                       
  geom_histogram(stat = "count", position = "dodge", alpha = 0.5, bins = 50) +
  theme_minimal()



```
```{r echo=FALSE, message=FALSE, warning=FALSE}
#GRAPHS SURVEY 2
survey_2 <- read_csv(here("outputs/data/survey_2.csv"))

ggplot(survey_2, aes(x = service_type, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_2, aes(x = disability, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_2, aes(x = woman, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_2, aes(x = visible, fill = group)) +                       
  geom_histogram(stat = "count", position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_2, aes(x = revenue, fill = group)) +                       
  geom_histogram(position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_2, aes(x = ft, fill = group)) +                       
  geom_histogram(position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()

ggplot(survey_2, aes(x = pt, fill = group)) +                       
  geom_histogram(position = "identity", alpha = 0.5, bins = 50) +
  theme_minimal()
```

```{r typeimpactcontrol, echo = FALSE, message = FALSE, warning = FALSE}
survey_2 %>% 
  filter(group == "control") %>%
  summary_factorlist("service_type", c("revenue", "ft", "pt"),
                     p = FALSE, 
                     add_dependent_label = TRUE, 
                     dependent_label_prefix = "",
                     add_col_totals = TRUE,
                     include_row_missing_col = FALSE,
                     col_totals_rowname = "",
                     col_totals_prefix = "N = ",
                     total_col = FALSE) %>%
  mutate(service_type = c("", "Revenue", "Number of full-time employees", "Number of part time employees")) %>%
  knitr::kable(caption = "Metrics of control group restaurants based on service type",
               booktabs = TRUE,
               col.names = c("Service Type", "", "Dine-in Only", "Takeout Only", "Both")) %>%
  kableExtra::kable_styling()
```

```{r typeimpacttreat, echo = FALSE, message = FALSE, warning = FALSE}
survey_2 %>% 
  filter(group == "treatment") %>%
  summary_factorlist("service_type", c("revenue", "ft", "pt"),
                     p = FALSE, 
                     add_dependent_label = TRUE, 
                     dependent_label_prefix = "",
                     add_col_totals = TRUE,
                     include_row_missing_col = FALSE,
                     col_totals_rowname = "",
                     col_totals_prefix = "N = ",
                     total_col = FALSE) %>%
  mutate(service_type = c("", "Revenue", "Number of full-time employees", "Number of part time employees")) %>%
  knitr::kable(caption = "Different impact on treatment restaurants based on service type",
               booktabs = TRUE,
               col.names = c("Service Type", "", "Dine-in Only", "Takeout Only", "Both")) %>%
  kableExtra::kable_styling()
```




```{r}
bind_rows(
  survey_2 %>%
    filter(indigenous == "yes" | visible == "yes") %>%
     mutate(minority = "Visible minority / Indigenous")
  ,
  survey_2 %>%
   filter(indigenous == "no" & visible == "no") %>%
    mutate(minority = "No")
) %>% 
  mutate(minority = fct_relevel(minority, "Visible minority / Indigenous", "No")) %>%
  ggplot(aes(x = minority, y = revenue / 1000, fill = group)) +
  geom_violin() +
  labs(fill = NULL,
       x = "Racial and ethnic minorities",
       y = "Mean revenue (in thousands of Canadian dollars") +
  theme_minimal()
```


```{r}
bind_rows(
  survey_2 %>%
    filter(indigenous == "yes" | visible == "yes") %>%
     mutate(minority = "Visible minority / Indigenous")
  ,
  survey_2 %>%
   filter(indigenous == "no" & visible == "no") %>%
    mutate(minority = "No")
) %>% 
  mutate(minority = fct_relevel(minority, "Visible minority / Indigenous", "No")) %>%
  ggplot(aes(x = minority, y = revenue / 1000, fill = group)) +
  geom_split_violin() +
  labs(fill = NULL,
       x = "Racial and ethnic minorities",
       y = "Mean revenue (in thousands of Canadian dollars") +
  theme_minimal()
```



```{r}
bind_rows(
  survey_2 %>%
    filter(indigenous == "yes" | visible == "yes") %>%
     mutate(minority = "Visible minority / Indigenous")
  ,
  survey_2 %>%
   filter(indigenous == "no" & visible == "no") %>%
    mutate(minority = "No")
) %>% 
  mutate(minority = fct_relevel(minority, "Visible minority / Indigenous", "No")) %>%
  ggplot(aes(x = minority, y = revenue / 1000, fill = group)) +
  geom_violin() +
  labs(fill = NULL,
       x = "Racial and ethnic minorities",
       y = "Mean revenue (in thousands of Canadian dollars") +
  theme_minimal()
```


```{r servicetypeimpactx, fig.cap="Revenues more heavily impacted for dine-in only establishments", fig.width=6, fig.height=4, echo = FALSE, message = FALSE, warning = FALSE, out.width = '70%', fig.align = "center"}
survey_2 %>%
  filter(service_type != "NA") %>%
  ggplot(aes(x = service_type, y = revenue / 1000, fill = group)) +
  geom_bar(position = "dodge", stat = "summary", fun.y = mean) +
  labs(fill = NULL,
       x = "Service type provided",
       y = "Mean revenue (in thousands of Canadian dollars") +
  scale_x_discrete(labels = c( "Dine-in Only", "Take-out only", "Both")) +
  theme_minimal()
```

```{r minorityimpactx, fig.cap="Minority-owned businesses were more heavily impacted", fig.width=4.5, fig.height=4, echo = FALSE, message = FALSE, warning = FALSE, out.width = '60%', fig.align = "center"}
bind_rows(
  survey_2 %>%
    filter(indigenous == "yes" | visible == "yes") %>%
     mutate(minority = "Visible minority / Indigenous")
  ,
  survey_2 %>%
   filter(indigenous == "no" & visible == "no") %>%
    mutate(minority = "No")
) %>% 
  mutate(minority = fct_relevel(minority, "Visible minority / Indigenous", "No")) %>%
  ggplot(aes(x = minority, y = revenue / 1000, fill = group)) +
  geom_bar(position = "dodge", stat = "summary", fun.y = mean) +
  labs(fill = NULL,
       x = "Racial and ethnic minorities",
       y = "Mean revenue (in thousands of Canadian dollars") +
  theme_minimal()
```



